export Access from './icons/access.svg'
export Ai from './icons/ai.svg'
export Excel from './icons/excel.svg'
export Figma from './icons/figma.svg'
export Photoshop from './icons/photoshop.svg'
export Powerpoint from './icons/powerpoint.svg'
export Sketch from './icons/sketch.svg'
export Word from './icons/word.svg'